-- OTOMATİK ÜRETİLDİ: npm run seed:generate (kaynak: seed/texts.json)

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('seviye-testi', 'Elif''in Yeni Komşusu', 'Elif, dokuz yaşında neşeli bir kızdı. Annesi ve küçük kardeşi Can ile birlikte mavi bir apartmanda oturuyordu. Bir cumartesi sabahı, kapının önünde büyük kutular gördü. Karşı daireye yeni bir aile taşınıyordu.

Kutuların arasında Elif''in yaşlarında bir kız vardı. Kız, elindeki saksıyı dikkatle taşıyordu. Saksıda küçük, sarı bir çiçek açmıştı. Elif hemen yanına gitti ve gülümseyerek "Merhaba, benim adım Elif. Sana yardım edebilir miyim?" dedi.

Kızın adı Zeynep''ti. Ailesiyle birlikte başka bir şehirden gelmişlerdi. Zeynep burada hiç kimseyi tanımıyordu ve biraz üzgündü. Elif ile konuşunca yüzü aydınlandı. İki kız birlikte hafif kutuları merdivenlerden yukarı taşıdılar. Can da oyuncak kamyonuyla küçük bir kutuyu getirmeye çalıştı. Herkes ona gülümsedi.

Öğleden sonra Elif''in annesi bir tepsi kurabiye pişirdi. Elif ve Can, kurabiyeleri yeni komşularına götürdüler. Zeynep''in annesi çok sevindi ve onlara teşekkür etti. Zeynep de Elif''e sarı çiçekli saksısından küçük bir fidan hediye etti.

O akşam Elif, fidanı penceresinin önüne koydu. Her sabah onu sulamaya karar verdi. Artık hem yeni bir çiçeği hem de yeni bir arkadaşı vardı.', 'Günlük Yaşam', 2, 3, 164, 123, 'system', 1);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Karşı daireye kim taşınıyordu?', 'Elif''in teyzesi', 'Yeni bir aile', 'Bir öğretmen', 'Yaşlı bir adam', 'b', 'Metinde karşı daireye yeni bir ailenin taşındığı söyleniyor.' FROM texts WHERE slug = 'seviye-testi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Zeynep elinde ne taşıyordu?', 'Bir kedi', 'Bir kitap', 'Bir saksı', 'Bir top', 'c', 'Zeynep, içinde sarı bir çiçek olan saksıyı dikkatle taşıyordu.' FROM texts WHERE slug = 'seviye-testi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Zeynep neden biraz üzgündü?', 'Burada hiç kimseyi tanımıyordu', 'Oyuncağı kırılmıştı', 'Çiçeği solmuştu', 'Kutular çok ağırdı', 'a', 'Zeynep başka bir şehirden gelmişti ve burada kimseyi tanımıyordu.' FROM texts WHERE slug = 'seviye-testi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Elif''in annesi yeni komşular için ne yaptı?', 'Çorba pişirdi', 'Çiçek aldı', 'Pasta satın aldı', 'Kurabiye pişirdi', 'd', 'Elif''in annesi bir tepsi kurabiye pişirdi, çocuklar da onları komşulara götürdü.' FROM texts WHERE slug = 'seviye-testi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metnin ana fikri nedir?', 'Taşınmak çok yorucudur.', 'Yeni gelenlere yardım etmek güzel dostluklar kurar.', 'Çiçekler her gün sulanmalıdır.', 'Kardeşler hep oyun oynar.', 'b', 'Elif, yeni komşusuna yardım ederek yeni bir arkadaş kazandı.' FROM texts WHERE slug = 'seviye-testi';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('minik-kedi-pamuk', 'Minik Kedi Pamuk', 'Ayşe''nin beyaz bir kedisi var. Kedinin adı Pamuk. Pamuk çok küçük ve çok tatlı. Tüyleri yumuşacık, gözleri yeşil.

Pamuk sabahları erkenden uyanır. Ayşe''nin yatağına zıplar. Kuyruğunu sallar ve miyavlar. Bu, onun günaydın deme şekli. Ayşe gülerek uyanır ve Pamuk''u sever.

Pamuk oyun oynamayı çok sever. En sevdiği oyuncak kırmızı bir yün yumağı. Ayşe yumağı yere atar. Pamuk hemen koşar ve yumağı yakalar. Bazen yumak halının altına kaçar. Pamuk onu bulana kadar arar.

Pamuk''un sevdiği bir yer de var. Bu yer, güneşli pencerenin kenarı. Öğleden sonra orada uzanır ve uyur. Güneş tüylerini ısıtır.

Kediler çok temiz hayvanlardır. Pamuk da her gün kendini diliyle yalar. Böylece tüylerini temizler. Ayşe de onun tüylerini yumuşak bir tarakla tarar.

Pamuk''un bir mama kabı ve bir su kabı var. Ayşe her gün kapları doldurur. Suyun temiz olmasına dikkat eder. Çünkü hayvanlar da bizim gibi temiz suya ihtiyaç duyar.

Akşam olunca Pamuk yorulur. Ayşe''nin kucağına kıvrılır. Mırıl mırıl ses çıkarır. Kediler mutlu olunca böyle mırlar. Ayşe, Pamuk''un en iyi arkadaşı olduğunu bilir.', 'Hayvanlar', 1, 2, 165, 124, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Pamuk''un gözleri ne renktir?', 'Mavi', 'Kahverengi', 'Yeşil', 'Sarı', 'c', 'Metinde Pamuk''un gözlerinin yeşil olduğu yazıyor.' FROM texts WHERE slug = 'minik-kedi-pamuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Pamuk''un en sevdiği oyuncak hangisidir?', 'Kırmızı bir yün yumağı', 'Küçük bir top', 'Bir tüy', 'Bir fare oyuncağı', 'a', 'Pamuk''un en sevdiği oyuncak kırmızı bir yün yumağıdır.' FROM texts WHERE slug = 'minik-kedi-pamuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Ayşe su kabının temiz olmasına neden dikkat eder?', 'Kap güzel görünsün diye', 'Annesi kızmasın diye', 'Pamuk suyla oynasın diye', 'Hayvanlar da temiz suya ihtiyaç duyduğu için', 'd', 'Metinde hayvanların da bizim gibi temiz suya ihtiyaç duyduğu söyleniyor.' FROM texts WHERE slug = 'minik-kedi-pamuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kediler mutlu olduklarında ne yapar?', 'Tıslar', 'Mırlar', 'Saklanır', 'Havlar', 'b', 'Kediler mutlu olunca mırıl mırıl ses çıkarır, yani mırlar.' FROM texts WHERE slug = 'minik-kedi-pamuk';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('bahcedeki-elma-agaci', 'Bahçedeki Elma Ağacı', 'Dedemin bahçesinde büyük bir elma ağacı var. Bu ağacı dedem yıllar önce dikmiş. Şimdi ağaç evden bile daha uzun.

İlkbaharda ağacın dalları beyaz ve pembe çiçeklerle dolar. Arılar çiçeklere konar. Vızır vızır uçarak çiçekten çiçeğe gider. Dedem arıların ağaca yardım ettiğini söyler. Arılar olmasa elmalar da olmazmış.

Yazın çiçekler dökülür. Yerlerinde küçük, yeşil elmalar belirir. Güneş parladıkça elmalar büyür. Yağmur yağdıkça ağaç su içer. Ben de ağacın gölgesinde oturup kitap okurum. Kuşlar dallarda şarkı söyler.

Sonbahar gelince elmalar kıpkırmızı olur. Dedemle birlikte sepetleri alırız. Alçak dallardaki elmaları ben toplarım. Yüksek dallardakileri dedem merdivenle toplar. Sepetlerimiz kısa sürede dolar. Annem bu elmalardan nefis bir reçel yapar.

Kışın ağacın hiç yaprağı kalmaz. Dalları çıplak görünür. Kar yağınca dallar beyaz bir örtüyle kaplanır. Ama dedem ağacın uyuduğunu söyler. Bahar gelince yeniden uyanacakmış.

Ben de büyüyünce kendi bahçeme bir elma ağacı dikmek istiyorum. Onu her gün sulayacağım. Belki bir gün benim torunlarım da onun gölgesinde oturur.', 'Doğa', 1, 2, 152, 114, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'İlkbaharda ağacın dalları neyle dolar?', 'Kırmızı elmalarla', 'Beyaz ve pembe çiçeklerle', 'Sarı yapraklarla', 'Karla', 'b', 'İlkbaharda dallar beyaz ve pembe çiçeklerle dolar.' FROM texts WHERE slug = 'bahcedeki-elma-agaci';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Yüksek dallardaki elmaları kim toplar?', 'Annem', 'Arılar', 'Ben', 'Dedem', 'd', 'Yüksek dallardaki elmaları dede merdivenle toplar.' FROM texts WHERE slug = 'bahcedeki-elma-agaci';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Dede, kışın ağaç için ne söyler?', 'Ağacın uyuduğunu', 'Ağacın hasta olduğunu', 'Ağacın kuruduğunu', 'Ağacın büyüdüğünü', 'a', 'Dede, kışın ağacın uyuduğunu ve baharda uyanacağını söyler.' FROM texts WHERE slug = 'bahcedeki-elma-agaci';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metnin ana fikri nedir?', 'Elma reçeli çok lezzetlidir.', 'Arılar insanları sokar.', 'Elma ağacı her mevsim değişir ve bize çok şey verir.', 'Kışın kar yağar.', 'c', 'Metin, elma ağacının dört mevsimde nasıl değiştiğini anlatıyor.' FROM texts WHERE slug = 'bahcedeki-elma-agaci';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('top-oynamayi-seviyorum', 'Top Oynamayı Seviyorum', 'Benim adım Emre. Ben futbol oynamayı çok seviyorum. Her hafta sonu arkadaşlarımla parkta top oynarız. Park, evimize çok yakın.

Önce iki takım kurarız. Bir takımda beş kişi, öbür takımda da beş kişi olur. Kaleleri taşlarla belirleriz. Sonra oyun başlar.

Ben genellikle kaleci olurum. Topu tutmak için sağa sola atlarım. Bazen yere düşerim ama hemen kalkarım. Kaleci olmak dikkat ister. Gözümü hiç toptan ayırmam.

Arkadaşım Deniz çok hızlı koşar. Topu alınca kimse ona yetişemez. Geçen hafta tam üç gol attı. Hepimiz onu alkışladık. Ama Deniz, gollerin takımın başarısı olduğunu söyledi. Çünkü ona pası biz vermiştik.

Maçtan önce mutlaka ısınırız. Biraz koşar, kollarımızı ve bacaklarımızı esnetiriz. Böylece kaslarımız incinmez. Ablam bize ısınma hareketlerini öğretti. Maçtan sonra da bol bol su içeriz.

Bazen kazanırız, bazen kaybederiz. Kaybettiğimizde üzülürüz ama küsmeyiz. Maç bitince rakip takımla el sıkışırız. Babam bana sporun en güzel yanının dostluk olduğunu öğretti. Ben de buna inanıyorum. Haftaya yine parkta buluşacağız.', 'Spor', 1, 2, 150, 113, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Emre maçlarda genellikle hangi görevde oynar?', 'Hakem', 'Forvet', 'Kaleci', 'Seyirci', 'c', 'Emre, genellikle kaleci olduğunu söylüyor.' FROM texts WHERE slug = 'top-oynamayi-seviyorum';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Deniz geçen hafta kaç gol attı?', 'Üç', 'İki', 'Bir', 'Dört', 'a', 'Metinde Deniz''in tam üç gol attığı yazıyor.' FROM texts WHERE slug = 'top-oynamayi-seviyorum';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Çocuklar maçtan önce neden ısınır?', 'Daha çok gol atmak için', 'Üşümemek için', 'Hakemi beklemek için', 'Kasları incinmesin diye', 'd', 'Isınma hareketleri sayesinde kaslarının incinmediği söyleniyor.' FROM texts WHERE slug = 'top-oynamayi-seviyorum';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metnin ana fikri nedir?', 'Kaleci olmak kolaydır.', 'Sporun en güzel yanı dostluktur.', 'Her maçı kazanmak gerekir.', 'Park evden uzaktır.', 'b', 'Emre, sporun en güzel yanının dostluk olduğuna inanıyor.' FROM texts WHERE slug = 'top-oynamayi-seviyorum';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('pazar-kahvaltisi', 'Pazar Kahvaltısı', 'Pazar günleri bizim evde çok güzel geçer. Çünkü o gün herkes evdedir. Kimse erkenden işe ya da okula gitmez.

Sabah ilk uyanan babamdır. Mutfağa gidip çayı demler. Çayın kokusu bütün eve yayılır. Sonra annem uyanır ve yumurtaları haşlar.

Ablam ile ben de sofrayı hazırlarız. Önce masaya temiz bir örtü sereriz. Tabakları, çatalları ve bardakları dizeriz. Ablam peyniri ve zeytinleri küçük kaselere koyar. Ben de domatesleri ve salatalıkları yıkarım. Annem onları dilimler.

Kahvaltıda taze ekmek de olmalı. Babam köşedeki fırından sıcacık ekmek alır. Ekmeğin kabuğu çıtır çıtırdır.

Hepimiz masaya oturunca sohbet başlar. Babam hafta boyunca neler yaptığımızı sorar. Ben okulda öğrendiğim şiiri okurum. Ablam resim kursundan bahseder. Annem de bize küçükken yaşadığı komik bir olayı anlatır. Hepimiz kahkahalarla güleriz.

Kahvaltı bitince masayı birlikte toplarız. Ben tabakları mutfağa taşırım. Ablam masayı siler. Babam bulaşıkları yıkar, annem de kurular. İş birlikte yapılınca çabucak biter.

Pazar kahvaltısı benim en sevdiğim andır. Çünkü o sofrada hepimiz bir aradayız.', 'Günlük Yaşam', 1, 2, 153, 115, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Pazar sabahı evde ilk kim uyanır?', 'Annem', 'Babam', 'Ablam', 'Ben', 'b', 'Metinde sabah ilk uyananın baba olduğu yazıyor.' FROM texts WHERE slug = 'pazar-kahvaltisi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Babam ekmeği nereden alır?', 'Marketten', 'Pazardan', 'Komşudan', 'Köşedeki fırından', 'd', 'Baba, köşedeki fırından sıcacık ekmek alır.' FROM texts WHERE slug = 'pazar-kahvaltisi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kahvaltıdan sonra masayı kim siler?', 'Ablam', 'Babam', 'Annem', 'Ben', 'a', 'Kahvaltıdan sonra masayı abla siler.' FROM texts WHERE slug = 'pazar-kahvaltisi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metnin ana fikri nedir?', 'Çay en güzel içecektir.', 'Pazar günü okula gidilmez.', 'Ailece birlikte vakit geçirmek güzeldir.', 'Bulaşık yıkamak zordur.', 'c', 'Anlatıcı, pazar kahvaltısını ailesiyle bir arada olduğu için sever.' FROM texts WHERE slug = 'pazar-kahvaltisi';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('ayi-taniyalim', 'Ay''ı Tanıyalım', 'Geceleri gökyüzüne baktığımızda en parlak gördüğümüz gök cismi genellikle Ay''dır. Ay, Dünya''nın çevresinde dönen doğal bir uydudur. Dünya''mızın yalnızca bir tane doğal uydusu vardır.

Ay çok parlak görünür ama aslında kendi ışığı yoktur. Güneş''ten gelen ışığı yansıtır. Tıpkı karanlık bir odada el fenerinin ışığını yansıtan bir ayna gibi.

Ay''ın şekli her gece biraz değişiyormuş gibi görünür. Bazen ince bir hilal, bazen yarım bir daire, bazen de yuvarlak bir dolunay görürüz. Aslında Ay''ın şekli hiç değişmez. Değişen, Güneş ışığının aydınlattığı kısmın bizden ne kadar göründüğüdür. Ay''ın bu evreleri yaklaşık bir ayda tamamlanır.

Ay, Dünya''dan yaklaşık 384 bin kilometre uzaktadır. Bir arabayla hiç durmadan gitsek oraya ulaşmamız aylar sürerdi. Ay''da hava yoktur. Bu yüzden orada rüzgâr esmez, yağmur yağmaz. Gökyüzü gündüz bile kapkara görünür.

1969 yılında Neil Armstrong, Ay''a ayak basan ilk insan oldu. Astronotların bıraktığı ayak izleri hâlâ oradadır. Çünkü Ay''da izleri silecek rüzgâr ya da yağmur yoktur. Bu izler milyonlarca yıl bozulmadan kalabilir.

Bu akşam pencereden Ay''a bakın. Bakalım bugün hangi evrede? Hilal mi, yarım ay mı, yoksa dolunay mı?', 'Uzay', 2, 3, 170, 128, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Ay''ın parlak görünmesini sağlayan ışık nereden gelir?', 'Kendi ateşinden', 'Yıldızlardan', 'Güneş''ten', 'Dünya''daki lambalardan', 'c', 'Ay''ın kendi ışığı yoktur, Güneş''ten gelen ışığı yansıtır.' FROM texts WHERE slug = 'ayi-taniyalim';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Ay''a ayak basan ilk insan kimdir?', 'Neil Armstrong', 'Yuri Gagarin', 'Isaac Newton', 'Galileo', 'a', '1969 yılında Neil Armstrong, Ay''a ayak basan ilk insan oldu.' FROM texts WHERE slug = 'ayi-taniyalim';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Astronotların ayak izleri Ay''da neden silinmez?', 'Ay''ın toprağı çok sert olduğu için', 'İzleri koruyan bir cam olduğu için', 'Ay çok soğuk olduğu için', 'İzleri silecek rüzgâr ve yağmur olmadığı için', 'd', 'Ay''da hava olmadığı için rüzgâr esmez, yağmur yağmaz.' FROM texts WHERE slug = 'ayi-taniyalim';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Ay''ın şekli neden değişiyormuş gibi görünür?', 'Ay her gece küçülüp büyüdüğü için', 'Aydınlanan kısmını bizden farklı gördüğümüz için', 'Bulutlar Ay''ı kestiği için', 'Ay kendi ışığını açıp kapattığı için', 'b', 'Ay''ın şekli değişmez; değişen, aydınlanan kısmın bizden ne kadar göründüğüdür.' FROM texts WHERE slug = 'ayi-taniyalim';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('kayip-harita', 'Kayıp Harita', 'Kerem ile Selin, yaz tatilini köyde, babaannelerinin yanında geçiriyordu. Bir öğleden sonra yağmur yağmaya başladı. Dışarı çıkamayan iki kardeş, evin tavan arasını keşfetmeye karar verdi.

Tavan arası tozlu eşyalarla doluydu. Eski bir sandığın içinde, sararmış bir kâğıt buldular. Kâğıdın üzerinde elle çizilmiş bir harita vardı. Haritada evin bahçesi, bir kuyu ve büyük bir ağaç görülüyordu. Ağacın yanına kırmızı kalemle bir çarpı işareti konmuştu.

"Bu bir hazine haritası!" diye bağırdı Selin. Yağmur dinince hemen bahçeye koştular. Haritaya göre önce eski kuyuyu bulmaları gerekiyordu. Kuyu, bahçenin arka köşesindeydi. Oradan on adım sağa yürüdüler ve kocaman bir ceviz ağacının önüne geldiler.

Kerem küçük bir kürekle ağacın dibini kazmaya başladı. Biraz sonra kürek sert bir şeye çarptı. Topraktan paslı, küçük bir teneke kutu çıktı. Kardeşler heyecanla kutuyu açtılar. İçinde renkli bilyeler, bir tahta düdük ve katlanmış bir mektup vardı.

Mektubu babaanneleri yazmıştı. Üstelik tam elli yıl önce! Mektupta şöyle diyordu: "Bu kutuyu bulan çocuk, benim en sevdiğim oyuncaklarıma artık sen iyi bak."

Kardeşler kutuyu babaannelerine götürdüler. Babaanneleri kutuyu görünce gözleri doldu ve gülümsedi. O akşam onlara çocukluğunu, oynadığı oyunları ve arkadaşlarını anlattı. Kerem ile Selin, en büyük hazinenin bu güzel anılar olduğunu anladılar.', 'Macera', 2, 3, 189, 142, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kardeşler haritayı nerede buldular?', 'Tavan arasındaki eski bir sandıkta', 'Bahçedeki kuyuda', 'Babaannelerinin çantasında', 'Ceviz ağacının dibinde', 'a', 'Harita, tavan arasındaki eski bir sandığın içindeydi.' FROM texts WHERE slug = 'kayip-harita';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Teneke kutu hangi ağacın dibinden çıktı?', 'Elma ağacının', 'Çınar ağacının', 'Ceviz ağacının', 'Kiraz ağacının', 'c', 'Kardeşler kocaman bir ceviz ağacının dibini kazdılar.' FROM texts WHERE slug = 'kayip-harita';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kutudaki mektubu kim yazmıştı?', 'Selin', 'Köyün muhtarı', 'Kerem''in öğretmeni', 'Babaanneleri', 'd', 'Mektubu elli yıl önce babaanneleri yazmıştı.' FROM texts WHERE slug = 'kayip-harita';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kardeşler neden en büyük hazinenin anılar olduğunu düşündüler?', 'Kutuda altın olmadığı için hayal kırıklığına uğradılar.', 'Kutu, babaannelerinin çocukluğunu ve güzel hatıralarını ortaya çıkardı.', 'Bilyeler çok eskiydi.', 'Harita yanlış çizilmişti.', 'b', 'Kutu sayesinde babaanneleri onlara çocukluğunu anlattı ve bu onları çok mutlu etti.' FROM texts WHERE slug = 'kayip-harita';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('robot-tobi', 'Robot Tobi', 'Bu yıl okulumuzda bir robotik kulübü açıldı. Öğretmenimiz Ahmet Bey, ilk gün masaya küçük, tekerlekli bir robot koydu. Robotun iki yuvarlak gözü ve parlak mavi bir gövdesi vardı. Ona hep birlikte Tobi adını verdik.

Ahmet Bey bize robotların kendi kendine düşünemediğini anlattı. "Robotlar, insanların verdiği komutlara göre hareket eder," dedi. "Bu komutların sırasına da kod denir." Kod yazmak, robota adım adım ne yapacağını söylemek demekti.

İlk görevimiz Tobi''yi sınıfın kapısına götürmekti. Tabletteki renkli blokları sıraya dizdik: "İleri git", "Sola dön", "İleri git". Sonra başlat düğmesine bastık. Ama Tobi sola değil, sağa döndü ve dolabın önünde durdu. Hepimiz güldük.

Kodumuzu tekrar inceledik. Meğer yanlışlıkla "Sağa dön" bloğunu seçmişiz. Ahmet Bey, "Hata yapmak öğrenmenin bir parçasıdır. Mühendisler de kodlarını defalarca dener," dedi. Bloğu değiştirdik ve yeniden denedik. Bu kez Tobi tam kapının önünde durdu. Sınıfça alkışladık.

Tobi''nin önünde küçük bir de sensör vardı. Sensör, robotun gözü gibi çalışıyordu. Önüne bir engel çıkınca Tobi bunu algılıyor ve duruyordu. Böylece hiçbir yere çarpmıyordu.

Artık her hafta Tobi''ye yeni görevler veriyoruz. Geçen hafta onu bir labirentten çıkardık. Ben büyüyünce insanlara yardım eden robotlar yapmak istiyorum.', 'Teknoloji', 2, 3, 180, 135, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Ahmet Bey''e göre kod nedir?', 'Robotun adı', 'Robotun pili', 'Komutların sırası', 'Tabletin şifresi', 'c', 'Ahmet Bey, komutların sırasına kod dendiğini anlattı.' FROM texts WHERE slug = 'robot-tobi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Tobi ilk denemede neden sağa döndü?', 'Çocuklar yanlışlıkla "Sağa dön" bloğunu seçmişti.', 'Tobi''nin pili bitmişti.', 'Sensör bozulmuştu.', 'Kapı kapalıydı.', 'a', 'Kodu incelediklerinde yanlış bloğu seçtiklerini fark ettiler.' FROM texts WHERE slug = 'robot-tobi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Tobi''nin sensörü ne işe yarar?', 'Müzik çalar', 'Işık yakar', 'Konuşmasını sağlar', 'Önündeki engelleri algılar', 'd', 'Sensör, önüne engel çıkınca Tobi''nin durmasını sağlıyordu.' FROM texts WHERE slug = 'robot-tobi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Ahmet Bey hata yapmak hakkında ne düşünüyor?', 'Hata yapmak utanç vericidir.', 'Hata yapmak öğrenmenin bir parçasıdır.', 'Mühendisler hiç hata yapmaz.', 'Hata yapan tekrar denememelidir.', 'b', 'Ahmet Bey, hata yapmanın öğrenmenin bir parçası olduğunu söyledi.' FROM texts WHERE slug = 'robot-tobi';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('kumsalda-kesif', 'Kumsalda Bir Keşif', 'Deniz, cumartesi sabahı babasıyla birlikte kumsala gitti. Yanına bir kova, bir büyüteç ve küçük bir defter aldı. Bugün bir kâşif gibi kumsalı inceleyecekti.

İlk olarak kıyıya vuran deniz kabuklarını topladı. Kabukların bazıları sarmal şeklindeydi, bazıları da yelpaze gibiydi. Babası bu kabukların bir zamanlar küçük deniz canlılarının evi olduğunu anlattı. Canlılar büyüdükçe kabukları da onlarla birlikte büyürmüş.

Sonra kayaların arasında hareket eden bir şey gördü. Bu küçük bir yengeçti! Yengeç, öne doğru değil yana doğru yürüyordu. Deniz onu büyüteçle dikkatlice izledi ama dokunmadı. Babası, yengecin korkunca kıskaçlarını kaldırdığını söyledi. Deniz defterine bir yengeç resmi çizdi.

Kıyıda yeşil ve kahverengi yosunlar da vardı. Yosunlar denizdeki birçok canlı için hem yiyecek hem de saklanma yeri oluyordu. Deniz, yosunların dokunulunca kaygan olduğunu fark etti.

Keşfin sonunda Deniz''in gözüne kumda parlayan bir şey çarptı. Yaklaşınca bunun plastik bir şişe olduğunu gördü. Biraz ötede bir poşet ve birkaç kapak daha vardı. Deniz çok üzüldü. Çünkü bu çöpler denizdeki canlılara zarar verebilirdi. Kaplumbağalar poşetleri yiyecek sanıp yutabilirdi.

Deniz ve babası çöpleri toplayıp çöp kutusuna attılar. Deniz defterine son bir not yazdı: "Kumsal, birçok canlının evidir. Onu temiz tutmalıyız."', 'Keşif', 2, 3, 181, 136, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Deniz kumsala giderken yanına neler aldı?', 'Top, havlu ve şapka', 'Kova, büyüteç ve defter', 'Olta, kova ve kürek', 'Kitap, kalem ve dürbün', 'b', 'Deniz yanına bir kova, bir büyüteç ve küçük bir defter aldı.' FROM texts WHERE slug = 'kumsalda-kesif';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Yengeç nasıl yürüyordu?', 'Öne doğru', 'Geriye doğru', 'Zıplayarak', 'Yana doğru', 'd', 'Metinde yengecin öne değil yana doğru yürüdüğü yazıyor.' FROM texts WHERE slug = 'kumsalda-kesif';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Deniz kumsalda çöp görünce neden üzüldü?', 'Çöpler denizdeki canlılara zarar verebileceği için', 'Kumsal çirkin göründüğü için', 'Oyun oynayacak yer kalmadığı için', 'Babası kızdığı için', 'a', 'Deniz, çöplerin deniz canlılarına zarar verebileceğini biliyordu.' FROM texts WHERE slug = 'kumsalda-kesif';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metnin ana fikri nedir?', 'Yengeçler tehlikeli hayvanlardır.', 'Deniz kabukları toplamak eğlencelidir.', 'Kumsal birçok canlının evidir ve temiz tutulmalıdır.', 'Yosunlar kaygandır.', 'c', 'Deniz''in son notu metnin ana fikrini özetliyor.' FROM texts WHERE slug = 'kumsalda-kesif';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('karincalarin-gizli-dunyasi', 'Karıncaların Gizli Dünyası', 'Bahçede yürürken yerde uzun bir çizgi hâlinde ilerleyen karıncaları hiç fark ettiniz mi? Bu minik canlılar, göründüklerinden çok daha düzenli ve çalışkan bir hayat sürer.

Karıncalar koloni adı verilen büyük gruplar hâlinde yaşar. Bir kolonide birkaç yüz karınca olabileceği gibi milyonlarca karınca da olabilir. Her koloninin bir kraliçesi vardır. Kraliçe karıncanın görevi yumurta bırakmaktır. Koloninin geri kalanı ise çoğunlukla işçi karıncalardan oluşur.

İşçi karıncaların pek çok görevi vardır. Bazıları yiyecek arar, bazıları yuvayı temizler, bazıları da yumurtalarla ve yavrularla ilgilenir. Bazı işçiler ise yuvanın girişinde bekçilik yapar. Böylece herkes kendi işini yaparak koloninin yaşamasına yardım eder.

Peki karıncalar neden hep aynı yoldan tek sıra hâlinde yürür? Yiyecek bulan bir karınca, yuvaya dönerken yere özel bir koku bırakır. Diğer karıncalar bu kokuyu takip ederek yiyeceğe ulaşır. Yani karıncalar, burnumuzun alamayacağı kokulardan yapılmış görünmez yollar çizer.

Karıncalar boylarına göre inanılmaz derecede güçlüdür. Bazı türler kendi ağırlıklarının onlarca katı yükü taşıyabilir. Bir insan bunu yapmaya kalksa bir arabayı sırtında taşıması gerekirdi!

Karıncaların yuvaları da çok ilginçtir. Toprağın altında birbirine bağlanan tüneller ve odalar bulunur. Bazı odalar yiyecek deposu, bazıları ise yavru odası olarak kullanılır.

Bir dahaki sefere bir karınca gördüğünüzde onu ezmeden izleyin. Belki de o an koloni için önemli bir görevi yerine getiriyordur.', 'Hayvanlar', 3, 3, 201, 151, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kraliçe karıncanın görevi nedir?', 'Yiyecek aramak', 'Yumurta bırakmak', 'Yuvayı korumak', 'Tünel kazmak', 'b', 'Metinde kraliçe karıncanın görevinin yumurta bırakmak olduğu yazıyor.' FROM texts WHERE slug = 'karincalarin-gizli-dunyasi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Karıncalar neden tek sıra hâlinde aynı yoldan yürür?', 'Kraliçe onlara yolu gösterdiği için', 'Gözleri çok iyi gördüğü için', 'Yere bırakılan özel kokuyu takip ettikleri için', 'Yol en kısa olduğu için', 'c', 'Yiyecek bulan karınca yere koku bırakır, diğerleri bu kokuyu izler.' FROM texts WHERE slug = 'karincalarin-gizli-dunyasi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Karınca yuvasında neler bulunur?', 'Birbirine bağlı tüneller ve odalar', 'Yalnızca tek bir büyük oda', 'Yapraklardan yapılmış duvarlar', 'Su dolu havuzlar', 'a', 'Toprağın altında birbirine bağlanan tüneller ve odalar bulunur.' FROM texts WHERE slug = 'karincalarin-gizli-dunyasi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metnin ana fikri nedir?', 'Karıncalar insanlara zarar verir.', 'Karıncalar yalnız yaşamayı sever.', 'Karıncalar yalnızca yaz aylarında çalışır.', 'Karıncalar iş birliği içinde, düzenli bir hayat sürer.', 'd', 'Metin, karıncaların görev paylaşımını ve düzenli yaşamını anlatıyor.' FROM texts WHERE slug = 'karincalarin-gizli-dunyasi';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('suyun-yolculugu', 'Suyun Yolculuğu', 'Bugün içtiğiniz bir bardak su, belki de milyonlarca yıl önce bir dinozorun içtiği suyun ta kendisi. Kulağa şaşırtıcı gelse de bu mümkün. Çünkü Dünya''daki su hiç kaybolmaz, yalnızca durmadan yolculuk eder. Bu yolculuğa su döngüsü denir.

Yolculuk, Güneş''in denizleri, gölleri ve nehirleri ısıtmasıyla başlar. Isınan suyun bir kısmı buharlaşır. Yani sıvı hâlden gaz hâline geçerek gözle göremediğimiz su buharına dönüşür. Su buharı, sıcak havayla birlikte gökyüzüne yükselir.

Yükseklere çıktıkça hava soğur. Soğuyan su buharı, minicik su damlacıklarına dönüşür. Bu olaya yoğuşma denir. Milyarlarca damlacık bir araya gelince bulutlar oluşur. Soğuk bir bardağın dış yüzeyinde biriken damlalar da aynı olayın küçük bir örneğidir.

Buluttaki damlacıklar birleşip büyüdükçe ağırlaşır. Sonunda hava onları taşıyamaz ve damlalar yeryüzüne düşer. Buna yağış denir. Hava çok soğuksa yağış kar ya da dolu olarak iner.

Yere düşen suyun bir kısmı nehirlere ve göllere akar. Bir kısmı toprağa süzülerek yer altı sularına karışır. Bitkiler de kökleriyle bu sudan faydalanır. Sonunda suyun büyük bölümü yeniden denizlere ulaşır. Güneş onu tekrar ısıtır ve yolculuk baştan başlar.

Su döngüsü sayesinde Dünya''daki bütün canlılar suya ulaşabilir. Ancak Dünya''daki suyun çok büyük bir kısmı tuzlu deniz suyudur. İçebileceğimiz temiz su ise oldukça azdır. Bu yüzden suyu dikkatli kullanmak, musluğu gereksiz yere açık bırakmamak hepimizin görevidir.', 'Bilim', 3, 3, 202, 152, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Su buharının soğuyarak minicik su damlacıklarına dönüşmesine ne denir?', 'Buharlaşma', 'Yağış', 'Yoğuşma', 'Donma', 'c', 'Metinde bu olaya yoğuşma dendiği açıklanıyor.' FROM texts WHERE slug = 'suyun-yolculugu';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Suyun yolculuğu neyle başlar?', 'Güneş''in suyu ısıtmasıyla', 'Kar yağmasıyla', 'Rüzgârın esmesiyle', 'Bitkilerin su içmesiyle', 'a', 'Yolculuk, Güneş''in denizleri, gölleri ve nehirleri ısıtmasıyla başlar.' FROM texts WHERE slug = 'suyun-yolculugu';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Hava çok soğuksa yağış nasıl iner?', 'Sis olarak', 'Buhar olarak', 'Yalnızca yağmur olarak', 'Kar ya da dolu olarak', 'd', 'Hava çok soğukken yağış kar ya da dolu olarak iner.' FROM texts WHERE slug = 'suyun-yolculugu';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metne göre suyu neden dikkatli kullanmalıyız?', 'Su döngüsü durduğu için', 'İçebileceğimiz temiz su az olduğu için', 'Su çok pahalı olduğu için', 'Denizler kuruduğu için', 'b', 'Dünya''daki suyun çoğu tuzludur, içilebilir temiz su azdır.' FROM texts WHERE slug = 'suyun-yolculugu';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('catalhoyuk', 'Çatalhöyük: Kapısı Çatıda Olan Evler', 'Konya Ovası''nda, bugünkü Çumra ilçesinin yakınında çok eski bir yerleşim yeri bulunur. Adı Çatalhöyük''tür. Bilim insanlarına göre burada yaklaşık dokuz bin yıl önce insanlar yaşıyordu. Bu da Çatalhöyük''ü dünyanın bilinen en eski yerleşim yerlerinden biri yapar.

Çatalhöyük''ün evleri, bugünkü evlerimize hiç benzemiyordu. Evler kerpiçten, yani çamur ve samanın karıştırılıp kurutulmasıyla yapılan tuğlalardan inşa edilmişti. En ilginç özelliği ise evlerin birbirine bitişik olmasıydı. Evlerin arasında sokak yoktu!

Peki insanlar evlerine nasıl giriyordu? Cevap çok şaşırtıcı: Çatıdan! Her evin çatısında bir açıklık vardı. İnsanlar bu açıklıktan ahşap bir merdivenle aşağı iner, evlerine öyle girerlerdi. Çatılar aynı zamanda bir sokak gibi kullanılırdı. Komşular çatıların üzerinde yürüyerek birbirlerini ziyaret ederdi.

Evlerin içinde yemek pişirmek için ocaklar, oturmak ve uyumak için yükseltilmiş sekiler bulunurdu. Duvarlar bazen kırmızı boyayla yapılmış resimlerle süslenirdi. Bu resimlerde hayvanlar, avcılar ve el izleri görülür.

Çatalhöyük halkı tarım yapmayı da biliyordu. Buğday ve arpa yetiştirir, koyun ve keçi beslerlerdi. Böylece yiyecek bulmak için sürekli yer değiştirmek zorunda kalmadılar. Bir yere yerleşip orada yaşamaya başlamak, insanlık tarihinde çok önemli bir adımdır.

Çatalhöyük, 2012 yılında UNESCO Dünya Mirası Listesi''ne alındı. Arkeologlar burada hâlâ kazı yapmakta ve yeni bilgiler bulmaktadır. Bugün burayı ziyaret edenler, binlerce yıl önce yaşamış insanların günlük hayatını yakından görebilir.', 'Tarih', 3, 4, 199, 149, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Çatalhöyük''te insanlar evlerine nasıl girerdi?', 'Ön kapıdan', 'Çatıdaki açıklıktan merdivenle', 'Pencereden atlayarak', 'Yer altındaki tünellerden', 'b', 'Her evin çatısında bir açıklık vardı ve insanlar merdivenle aşağı inerdi.' FROM texts WHERE slug = 'catalhoyuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Çatalhöyük''ün evleri neyle yapılmıştı?', 'Taş ve mermerle', 'Ahşap ve camla', 'Demir ve betonla', 'Kerpiçle', 'd', 'Evler, çamur ve samandan yapılan kerpiç tuğlalarla inşa edilmişti.' FROM texts WHERE slug = 'catalhoyuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Çatalhöyük halkı neden sürekli yer değiştirmek zorunda kalmadı?', 'Tarım yapıp hayvan besledikleri için', 'Evleri çok büyük olduğu için', 'Başka yerler çok soğuk olduğu için', 'Yürümeyi sevmedikleri için', 'a', 'Buğday ve arpa yetiştirip koyun ve keçi besledikleri için yiyecekleri yanlarındaydı.' FROM texts WHERE slug = 'catalhoyuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Çatalhöyük hangi ilimizdedir?', 'İzmir', 'Ankara', 'Konya', 'Trabzon', 'c', 'Çatalhöyük, Konya Ovası''nda, Çumra ilçesi yakınındadır.' FROM texts WHERE slug = 'catalhoyuk';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('maratonun-hikayesi', 'Maratonun Hikâyesi', 'Maraton, 42 kilometre 195 metre uzunluğunda bir koşu yarışıdır. Bugün dünyanın pek çok şehrinde maratonlar düzenlenir. İstanbul Maratonu ise koşucuların Asya''dan Avrupa''ya geçtiği, kıtalar arasında koşulan ender yarışlardan biridir. Peki bu yarışın adı nereden geliyor?

Maraton, adını Yunanistan''daki Maraton adlı bir ovadan alır. Anlatılan bir efsaneye göre yaklaşık iki bin beş yüz yıl önce burada büyük bir savaş olmuştur. Savaş bittikten sonra Filipides adında bir haberci, zafer haberini Atina şehrine ulaştırmak için yola çıkmıştır. Hiç durmadan yaklaşık kırk kilometre koşmuş ve haberi vermiştir. Efsaneye göre haberci, bu büyük çabanın ardından bitkin bir hâlde yere yığılmıştır.

Tarihçiler bu hikâyenin tam olarak böyle yaşanıp yaşanmadığından emin değildir. Ama efsane o kadar sevilmiştir ki yüzyıllar boyunca anlatılmaya devam etmiştir.

1896 yılında Atina''da ilk modern Olimpiyat Oyunları düzenlendi. Düzenleyiciler, bu eski efsaneyi anmak için Maraton''dan Atina''ya uzanan bir koşu yarışı eklediler. Böylece maraton yarışı doğmuş oldu. Yarışın bugünkü uzunluğu ise ilk kez 1908 Londra Olimpiyatları''nda kullanıldı, daha sonra da resmî mesafe olarak kabul edildi.

Maraton koşmak büyük bir dayanıklılık ister. Koşucular aylarca antrenman yapar, dengeli beslenir ve bol su içer. Yarış sırasında enerjilerini dikkatli kullanmaları gerekir. Çok hızlı başlayan bir koşucu, bitişe varmadan yorulabilir.

Maratonda herkes birinci olmak için koşmaz. Birçok kişi için asıl amaç, kendi sınırlarını zorlamak ve yarışı bitirebilmektir. Bitiş çizgisini geçen her koşucu, kendi zaferini kazanmış olur.', 'Spor', 3, 4, 216, 162, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Maraton yarışı adını nereden alır?', 'Ünlü bir koşucudan', 'Bir Yunan tanrısından', 'Yunanistan''daki bir ovadan', 'İstanbul''daki bir semtten', 'c', 'Maraton, adını Yunanistan''daki Maraton Ovası''ndan alır.' FROM texts WHERE slug = 'maratonun-hikayesi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'İlk modern Olimpiyat Oyunları ne zaman ve nerede yapıldı?', '1896''da Atina''da', '1908''de Londra''da', '1900''de Paris''te', '1896''da İstanbul''da', 'a', 'İlk modern Olimpiyat Oyunları 1896 yılında Atina''da düzenlendi.' FROM texts WHERE slug = 'maratonun-hikayesi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metinde Filipides''in hikâyesi için ne söyleniyor?', 'Kesin olarak yaşanmış bir olaydır.', 'Kesin olarak yaşandığı bilinmeyen bir efsanedir.', 'Bir çizgi filmden alınmıştır.', '1908 yılında yaşanmıştır.', 'b', 'Tarihçiler hikâyenin böyle yaşanıp yaşanmadığından emin değildir; bu bir efsanedir.' FROM texts WHERE slug = 'maratonun-hikayesi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metne göre birçok maraton koşucusunun asıl amacı nedir?', 'Para ödülü kazanmak', 'Herkesi geçmek', 'Madalya toplamak', 'Kendi sınırlarını zorlamak ve yarışı bitirmek', 'd', 'Birçok koşucu için asıl amaç kendi sınırlarını zorlamak ve yarışı bitirmektir.' FROM texts WHERE slug = 'maratonun-hikayesi';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('fenerdeki-firtinali-gece', 'Fenerdeki Fırtınalı Gece', 'Ege kıyısındaki küçük bir adada, yaşlı bir deniz feneri vardı. Fenerin bekçisi Hasan Dede''ydi. On yaşındaki torunu Mert, o yaz dedesinin yanında kalıyordu. Mert her akşam dedesiyle birlikte fenerin döner merdivenlerini tırmanır, büyük lambanın yanmasını izlerdi.

Hasan Dede, fenerin gemiler için çok önemli olduğunu anlatırdı. "Karanlıkta kaptanlar kayalıkları göremez," derdi. "Fenerin ışığı onlara nereden uzak durmaları gerektiğini gösterir."

Bir gece adaya şiddetli bir fırtına geldi. Rüzgâr uğulduyor, dalgalar kayalara çarpıyordu. Tam o sırada elektrikler kesildi ve fenerin lambası söndü. Mert pencereden baktığında uzakta, dalgaların arasında küçük bir balıkçı teknesinin ışığını gördü. Tekne, ada kıyısındaki tehlikeli kayalıklara doğru ilerliyordu.

Hasan Dede hemen harekete geçti. "Çabuk, jeneratörü çalıştırmama yardım et!" dedi. Mert korkuyordu ama cesaretini topladı. Yağmurun altında el feneriyle dedesinin önünü aydınlattı. Birlikte depoya ulaştılar. Dede jeneratörü çalıştırmaya uğraşırken Mert de ona gereken aletleri uzattı.

Birkaç denemeden sonra jeneratör homurdanarak çalıştı. Fenerin lambası yeniden parladı ve güçlü ışık denizi taradı. Balıkçı teknesi hemen yön değiştirdi ve kayalıklardan uzaklaşarak limana doğru ilerledi.

Ertesi sabah balıkçı, elinde taze balıklarla fenere geldi ve teşekkür etti. Hasan Dede, Mert''in omzuna elini koydu. "Bu gece gerçek bir fener bekçisi gibiydin," dedi. Mert, cesaretin korkmamak değil, korksa da doğru olanı yapmak olduğunu öğrenmişti.', 'Macera', 3, 3, 196, 147, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Hasan Dede''ye göre fener gemiler için neden önemlidir?', 'Kaptanlara tehlikeli kayalıkları gösterdiği için', 'Gemilere yakıt verdiği için', 'Balıkları kıyıya çektiği için', 'Saatin kaç olduğunu gösterdiği için', 'a', 'Fenerin ışığı kaptanlara nereden uzak durmaları gerektiğini gösterir.' FROM texts WHERE slug = 'fenerdeki-firtinali-gece';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Fenerin lambası neden söndü?', 'Ampul patladığı için', 'Hasan Dede lambayı kapattığı için', 'Elektrikler kesildiği için', 'Lambaya su girdiği için', 'c', 'Fırtına sırasında elektrikler kesildi ve lamba söndü.' FROM texts WHERE slug = 'fenerdeki-firtinali-gece';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Mert dedesine nasıl yardım etti?', 'Balıkçıya telefon etti', 'El feneriyle yolu aydınlattı ve aletleri uzattı', 'Tekneye yüzerek gitti', 'Lambayı tamir etti', 'b', 'Mert, el feneriyle dedesinin önünü aydınlattı ve ona aletleri uzattı.' FROM texts WHERE slug = 'fenerdeki-firtinali-gece';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Mert bu olaydan ne öğrendi?', 'Fırtınaların hiç tehlikeli olmadığını', 'Balık tutmanın kolay olduğunu', 'Jeneratörün nasıl yapıldığını', 'Cesaretin, korksa da doğru olanı yapmak olduğunu', 'd', 'Metnin sonunda Mert''in cesaretle ilgili öğrendiği açıkça yazıyor.' FROM texts WHERE slug = 'fenerdeki-firtinali-gece';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('yapraklar-neden-sararir', 'Yapraklar Neden Sararır?', 'Sonbaharda parklarda yürürken ayaklarımızın altında hışırdayan sarı, turuncu ve kırmızı yapraklar görürüz. Oysa yazın aynı ağaçlar yemyeşildi. Peki yapraklar neden renk değiştirir?

Bu sorunun cevabı yaprakların içinde saklıdır. Yapraklarda klorofil adı verilen yeşil bir madde bulunur. Klorofil, bitkinin Güneş ışığını kullanarak kendi besinini üretmesini sağlar. Bitkiler bu sırada havadaki karbondioksiti alır ve bizim soluduğumuz oksijeni verir. Bu olaya fotosentez denir. Yazın yapraklarda çok fazla klorofil olduğu için yapraklar yeşil görünür.

Aslında yaprakların içinde sarı ve turuncu renkli başka maddeler de vardır. Ancak yazın klorofilin güçlü yeşil rengi bu renkleri gizler.

Sonbahar gelince günler kısalır ve havalar soğur. Ağaçlar artık eskisi kadar Güneş ışığı alamaz. Bu yüzden klorofil üretmeyi yavaş yavaş bırakırlar. Yapraklardaki klorofil azaldıkça yeşil renk kaybolur. Böylece yaz boyunca saklanan sarı ve turuncu renkler ortaya çıkar. Bazı ağaçların yaprakları ise sonbaharda oluşan yeni maddeler sayesinde kırmızıya döner.

Bir süre sonra ağaçlar yapraklarını döker. Bu, kışa hazırlanmanın bir yoludur. Yapraksız kalan ağaçlar soğuk kış aylarında daha az su kaybeder ve adeta dinlenir. Dökülen yapraklar da boşa gitmez. Toprağın üzerinde çürüyerek toprağı besler ve küçük canlılara yuva olur.

İlkbahar geldiğinde dallarda yeni tomurcuklar belirir. Ağaçlar yeniden klorofil üretmeye başlar ve doğa tekrar yeşile bürünür. Böylece doğanın bu güzel döngüsü her yıl yeniden tekrarlanır.', 'Doğa', 3, 3, 202, 152, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Yapraklara yeşil rengini veren madde hangisidir?', 'Oksijen', 'Klorofil', 'Karbondioksit', 'Su', 'b', 'Yapraklarda bulunan klorofil yeşil renklidir.' FROM texts WHERE slug = 'yapraklar-neden-sararir';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Ağaçlar sonbaharda neden klorofil üretmeyi bırakır?', 'Yapraklar yaşlandığı için', 'Yağmur çok yağdığı için', 'Kuşlar yaprakları yediği için', 'Günler kısalıp daha az Güneş ışığı aldıkları için', 'd', 'Sonbaharda günler kısalır ve ağaçlar eskisi kadar Güneş ışığı alamaz.' FROM texts WHERE slug = 'yapraklar-neden-sararir';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Dökülen yapraklara ne olur?', 'Çürüyerek toprağı besler', 'Rüzgârla uzaya uçar', 'Yeniden dallara yapışır', 'Taşa dönüşür', 'a', 'Dökülen yapraklar toprağın üzerinde çürüyerek toprağı besler.' FROM texts WHERE slug = 'yapraklar-neden-sararir';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Yapraklardaki sarı ve turuncu renkler yazın neden görünmez?', 'Yazın bu renkler hiç yoktur.', 'Güneş bu renkleri soldurur.', 'Klorofilin güçlü yeşil rengi onları gizler.', 'Yapraklar yazın çok küçüktür.', 'c', 'Sarı ve turuncu maddeler yazın da vardır ama yeşil klorofil onları gizler.' FROM texts WHERE slug = 'yapraklar-neden-sararir';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('gunes-sisteminde-yolculuk', 'Güneş Sistemi''nde Bir Yolculuk', 'Hayal gücümüzü kullanarak bir uzay gemisine bindiğimizi düşünelim. Yolculuğumuz Güneş Sistemi''nin merkezinden, yani Güneş''ten başlıyor. Güneş aslında bir yıldızdır. Bize diğer yıldızlardan çok daha büyük ve parlak görünmesinin nedeni, Dünya''ya çok daha yakın olmasıdır. Güneş''in içine yaklaşık bir milyon Dünya sığabilir. Işığı ve ısısı olmasaydı gezegenimizde yaşam mümkün olmazdı.

Güneş''in çevresinde sekiz gezegen döner. Güneş''e en yakın gezegen Merkür''dür. Merkür en küçük gezegendir ve Güneş''in çevresini çok hızlı dolaşır. Bir yılı yalnızca 88 gün sürer. İkinci gezegen Venüs''tür. Venüs, Güneş''e Merkür kadar yakın olmamasına rağmen en sıcak gezegendir. Çünkü kalın atmosferi, ısıyı bir battaniye gibi hapseder.

Üçüncü sırada evimiz Dünya bulunur. Bildiğimiz kadarıyla yaşamın olduğu tek gezegen burasıdır. Sıvı suyun bulunması, uygun sıcaklık ve soluduğumuz hava, Dünya''yı özel yapar. Dördüncü gezegen Mars''tır. Toprağındaki paslı demir tozları nedeniyle kırmızı görünür. Bilim insanları, Mars''a robot araçlar göndererek orada geçmişte su olup olmadığını araştırmaktadır.

Mars''ı geçtikten sonra dev gezegenlere ulaşırız. Jüpiter, Güneş Sistemi''nin en büyük gezegenidir. Yüzeyinde yüzyıllardır dinmeyen dev bir fırtına vardır. Satürn ise buz ve kaya parçalarından oluşan muhteşem halkalarıyla tanınır. Onları, soğuk ve uzak gezegenler Uranüs ile Neptün izler. Neptün''de Güneş Sistemi''nin en hızlı rüzgârları eser.

Bu gezegenler arasındaki mesafeler akıl almaz derecede büyüktür. Güneş''ten çıkan ışık, saniyede yaklaşık üç yüz bin kilometre hızla ilerlediği hâlde Dünya''ya ancak sekiz dakikada ulaşır.

Hayali uzay yolculuğumuz burada bitiyor. Ama evren, keşfedilmeyi bekleyen sayısız sırla dolu.', 'Uzay', 4, 4, 223, 167, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Güneş Sistemi''nin en sıcak gezegeni hangisidir?', 'Merkür', 'Mars', 'Venüs', 'Jüpiter', 'c', 'Metinde Venüs''ün en sıcak gezegen olduğu yazıyor.' FROM texts WHERE slug = 'gunes-sisteminde-yolculuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Venüs, Güneş''e daha yakın olan Merkür''den neden daha sıcaktır?', 'Kalın atmosferi ısıyı hapsettiği için', 'Daha büyük olduğu için', 'Üzerinde yanardağlar olduğu için', 'Daha yavaş döndüğü için', 'a', 'Venüs''ün kalın atmosferi ısıyı bir battaniye gibi hapseder.' FROM texts WHERE slug = 'gunes-sisteminde-yolculuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Mars neden kırmızı görünür?', 'Çok sıcak olduğu için', 'Toprağındaki paslı demir tozları nedeniyle', 'Üzerinde kırmızı bitkiler olduğu için', 'Güneş''e en yakın gezegen olduğu için', 'b', 'Mars''ın toprağındaki paslı demir tozları ona kırmızı rengini verir.' FROM texts WHERE slug = 'gunes-sisteminde-yolculuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Güneş''ten çıkan ışık Dünya''ya yaklaşık kaç dakikada ulaşır?', 'Bir dakikada', 'Otuz dakikada', 'Altmış dakikada', 'Sekiz dakikada', 'd', 'Işık çok hızlı olmasına rağmen Dünya''ya ancak sekiz dakikada ulaşır.' FROM texts WHERE slug = 'gunes-sisteminde-yolculuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Güneş, bize diğer yıldızlardan neden daha büyük ve parlak görünür?', 'Evrenin en büyük yıldızı olduğu için', 'Gezegen olduğu için', 'Dünya''ya çok daha yakın olduğu için', 'Yalnızca gündüz parladığı için', 'c', 'Güneş de bir yıldızdır; bize çok daha yakın olduğu için büyük ve parlak görünür.' FROM texts WHERE slug = 'gunes-sisteminde-yolculuk';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('piri-reis-haritasi', 'Piri Reis ve Ünlü Haritası', 'Günümüzde bir yere gitmek istediğimizde telefonumuzdaki haritaya bakmamız yeterli. Uydular sayesinde dünyanın her köşesini görebiliyoruz. Peki uyduların, uçakların, hatta fotoğraf makinelerinin bile olmadığı zamanlarda haritalar nasıl çiziliyordu? Bu sorunun en ünlü cevaplarından biri, Osmanlı denizcisi Piri Reis''tir.

Piri Reis, yaklaşık 1470 yılında Gelibolu''da doğdu. Gençliğinde, ünlü denizci amcası Kemal Reis''in yanında denizlere açıldı. Akdeniz''in limanlarını, adalarını ve kıyılarını yakından tanıdı. Gördüğü her yeri dikkatle inceliyor, notlar alıyordu.

1513 yılında Piri Reis, bugün dünyaca ünlü olan haritasını çizdi. Harita, ceylan derisi üzerine renkli mürekkeplerle çizilmişti. Haritada Avrupa''nın ve Afrika''nın batı kıyıları, Atlas Okyanusu ve Güney Amerika''nın kıyıları yer alıyordu. O yıllarda Amerika kıtası Avrupalılar tarafından yeni tanınmaya başlamıştı. Bu nedenle harita, döneminin en dikkat çekici çalışmalarından biri kabul edilir.

Piri Reis bu haritayı hazırlarken yirmi kadar eski haritadan yararlandığını yazmıştır. Bunların arasında Kristof Kolomb''un çizdiği bir haritanın da bulunduğunu belirtmiştir. Yani Piri Reis, farklı kaynaklardan gelen bilgileri karşılaştırarak birleştiren titiz bir bilim insanı gibi çalışmıştır.

Piri Reis, 1521 yılında Kitab-ı Bahriye adlı eserini de tamamladı. Bu kitap, denizciler için hazırlanmış bir rehberdi. Kitapta limanlar, rüzgârlar, sığ yerler ve tehlikeli kayalıklar hakkında ayrıntılı bilgiler ve çizimler vardı. Denizciler bu bilgiler sayesinde daha güvenli yolculuk yapabiliyordu.

Ünlü haritanın günümüze ulaşan parçası, 1929 yılında Topkapı Sarayı''nda bulundu. Bugün hâlâ orada özenle korunmaktadır. UNESCO, haritanın çiziminin beş yüzüncü yılı nedeniyle 2013 yılını Piri Reis Yılı ilan etti.', 'Tarih', 4, 4, 222, 167, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Piri Reis''in 1513 yılındaki haritası neyin üzerine çizilmişti?', 'Kâğıdın', 'Ceylan derisinin', 'Tahta bir levhanın', 'İpek kumaşın', 'b', 'Harita, ceylan derisi üzerine renkli mürekkeplerle çizilmişti.' FROM texts WHERE slug = 'piri-reis-haritasi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kitab-ı Bahriye nasıl bir eserdir?', 'Bir masal kitabı', 'Bir yemek kitabı', 'Bir şiir kitabı', 'Denizciler için hazırlanmış bir rehber', 'd', 'Kitab-ı Bahriye; limanlar, rüzgârlar ve tehlikeli yerler hakkında bilgi veren bir denizcilik rehberidir.' FROM texts WHERE slug = 'piri-reis-haritasi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Haritanın günümüze ulaşan parçası nerede bulundu?', 'Topkapı Sarayı''nda', 'Gelibolu''da bir evde', 'Bir gemi enkazında', 'Yurt dışındaki bir müzede', 'a', 'Harita parçası 1929 yılında Topkapı Sarayı''nda bulundu.' FROM texts WHERE slug = 'piri-reis-haritasi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Piri Reis''in çalışma yöntemi hakkında hangisi söylenebilir?', 'Hiçbir kaynağa bakmadan çizmiştir.', 'Haritayı uydu fotoğraflarından çizmiştir.', 'Farklı kaynakları karşılaştırarak titizlikle çalışmıştır.', 'Haritayı yalnızca hayal gücüyle çizmiştir.', 'c', 'Piri Reis, yirmi kadar eski haritadan yararlanıp bilgileri karşılaştırmıştır.' FROM texts WHERE slug = 'piri-reis-haritasi';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('internet-nasil-calisir', 'İnternet Nasıl Çalışır?', 'Bir videoyu izlemek, bir oyunu oynamak ya da uzaktaki bir akrabamızla görüntülü konuşmak için internete bağlanırız. Birkaç saniye içinde başka bir şehirden, hatta başka bir kıtadan bilgiler ekranımıza gelir. Peki bu bilgiler bize nasıl ulaşıyor?

İnternet, dünyanın dört bir yanındaki milyonlarca bilgisayarın birbirine bağlanmasıyla oluşan dev bir ağdır. Bu ağı, birbirine bağlı yolların oluşturduğu kocaman bir haritaya benzetebiliriz. Bilgiler de bu yollarda yolculuk eden araçlar gibidir.

İnternette gönderilen her bilgi, yola çıkmadan önce paket adı verilen küçük parçalara bölünür. Örneğin bir fotoğraf, yüzlerce minik pakete ayrılır. Her paketin üzerinde, tıpkı bir mektup zarfındaki gibi, nereden gelip nereye gideceğini gösteren bir adres yazılıdır. Paketler bazen farklı yollardan gider ama hedefe ulaşınca bilgisayar onları doğru sırayla birleştirir. Böylece fotoğraf ekranımızda eksiksiz görünür.

Bu paketler nasıl taşınır? Evlerimizde bilgiler çoğunlukla modemden cihazlarımıza kablosuz olarak iletilir. Ancak uzun mesafelerde genellikle kablolar kullanılır. Hatta okyanusların dibinde, kıtaları birbirine bağlayan binlerce kilometrelik fiber optik kablolar vardır. Bu kablolar bilgileri ışık sinyalleri hâlinde son derece hızlı taşır.

İzlediğimiz videolar ve ziyaret ettiğimiz siteler, sunucu adı verilen güçlü bilgisayarlarda saklanır. Bir siteye girmek istediğimizde bilgisayarımız sunucuya bir istek gönderir. Sunucu da istenen bilgileri paketler hâlinde bize yollar. Bütün bunlar göz açıp kapayıncaya kadar gerçekleşir.

İnternet bize öğrenmek ve iletişim kurmak için harika fırsatlar sunar. Ama onu güvenli kullanmak da önemlidir. Kişisel bilgilerimizi tanımadığımız kişilerle paylaşmamalı, bir sorunla karşılaştığımızda mutlaka bir büyüğümüze haber vermeliyiz.', 'Teknoloji', 4, 4, 225, 169, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'İnternette bir bilgi gönderilmeden önce ne olur?', 'Paket adı verilen küçük parçalara bölünür', 'Kâğıda yazdırılır', 'Bir kutuya konur', 'Renkli ışıklara boyanır', 'a', 'Her bilgi yola çıkmadan önce paket adı verilen küçük parçalara bölünür.' FROM texts WHERE slug = 'internet-nasil-calisir';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Okyanusların dibinde kıtaları birbirine bağlayan nedir?', 'Tüneller', 'Uydular', 'Fiber optik kablolar', 'Denizaltılar', 'c', 'Okyanus diplerinde binlerce kilometrelik fiber optik kablolar vardır.' FROM texts WHERE slug = 'internet-nasil-calisir';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metne göre sunucu nedir?', 'İnternet faturası', 'Bir oyun türü', 'Evdeki modem', 'Videoların ve sitelerin saklandığı güçlü bilgisayar', 'd', 'Videolar ve siteler, sunucu adı verilen güçlü bilgisayarlarda saklanır.' FROM texts WHERE slug = 'internet-nasil-calisir';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'İnterneti güvenli kullanmak için ne yapmalıyız?', 'Şifremizi arkadaşlarımıza söylemeliyiz.', 'Kişisel bilgilerimizi tanımadığımız kişilerle paylaşmamalıyız.', 'Her gördüğümüz bağlantıya tıklamalıyız.', 'Sorunları kimseye anlatmamalıyız.', 'b', 'Metinde kişisel bilgileri tanımadığımız kişilerle paylaşmamamız gerektiği söyleniyor.' FROM texts WHERE slug = 'internet-nasil-calisir';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('kutuplara-yolculuk', 'Kutuplara Yolculuk', 'Dünya''mızın en soğuk ve en ıssız yerleri, kutup bölgeleridir. Gezegenimizin en kuzeyinde Kuzey Kutbu, en güneyinde ise Güney Kutbu bulunur. Bu iki bölge birbirine benzese de aralarında önemli farklar vardır.

Kuzey Kutbu''nun çevresindeki bölgeye Arktik denir. Kuzey Kutbu bir kara parçası üzerinde değildir. Donmuş bir okyanusun, yani Arktik Okyanusu''nun ortasındadır. Deniz buzlarının üzerinde kutup ayıları dolaşır. Kalın kürkleri ve derilerinin altındaki yağ tabakası onları soğuktan korur.

Güney Kutbu ise Antarktika adlı bir kıtanın üzerindedir. Antarktika''nın neredeyse tamamı kalın bir buz tabakasıyla örtülüdür. Bu buz bazı yerlerde birkaç kilometre kalınlığa ulaşır. Dünya''da ölçülen en düşük sıcaklıklar da bu kıtada kaydedilmiştir. Penguenler bu bölgenin en tanınmış canlılarıdır. İlginçtir ki kutup ayıları ile penguenler doğada hiç karşılaşmaz, çünkü biri kuzeyde, diğeri güneyde yaşar.

Kutuplarda gece ve gündüz de alıştığımızdan farklıdır. Dünya''nın ekseni eğik olduğu için kutuplarda yaz aylarında Güneş hiç batmaz. Kış aylarında ise aylarca doğmaz. Yani kutuplarda bir yılın yaklaşık altı ayı gündüz, altı ayı gece gibidir.

Antarktika''da kalıcı olarak yaşayan insan yoktur. Ancak pek çok ülkenin bilim insanları burada kurulan araştırma istasyonlarında çalışır. Buzun içindeki eski hava kabarcıklarını inceleyerek binlerce yıl önceki iklim hakkında bilgi edinirler. Türkiye de 2017 yılından bu yana Antarktika''ya düzenli olarak bilimsel seferler düzenlemektedir.

Kutuplardaki buzlar, dünya ikliminin dengesi için çok önemlidir. Bu yüzden bilim insanları, iklim değişikliğinin kutupları nasıl etkilediğini dikkatle izlemektedir.', 'Keşif', 4, 4, 216, 162, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kuzey Kutbu nerede bulunur?', 'Bir kıtanın ortasında', 'Donmuş bir okyanusun ortasında', 'Yüksek bir dağın tepesinde', 'Bir adanın üzerinde', 'b', 'Kuzey Kutbu, donmuş Arktik Okyanusu''nun ortasındadır.' FROM texts WHERE slug = 'kutuplara-yolculuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kutup ayıları ile penguenler doğada neden hiç karşılaşmaz?', 'Penguenler kutup ayılarından saklandığı için', 'İkisi de kış uykusuna yattığı için', 'Kutup ayıları yüzemediği için', 'Biri kuzeyde, diğeri güneyde yaşadığı için', 'd', 'Kutup ayıları kuzeyde, penguenler ise güneyde yaşar.' FROM texts WHERE slug = 'kutuplara-yolculuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Kutuplarda yaz aylarında ne olur?', 'Güneş hiç batmaz', 'Güneş hiç doğmaz', 'Bütün buzlar erir', 'Her gün yağmur yağar', 'a', 'Dünya''nın ekseni eğik olduğu için kutuplarda yazın Güneş hiç batmaz.' FROM texts WHERE slug = 'kutuplara-yolculuk';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Bilim insanları buzun içindeki eski hava kabarcıklarını neden inceler?', 'İçme suyu elde etmek için', 'Penguenleri saymak için', 'Binlerce yıl önceki iklimi öğrenmek için', 'Yeni buz yapmak için', 'c', 'Bu kabarcıklar, geçmişteki iklim hakkında bilgi verir.' FROM texts WHERE slug = 'kutuplara-yolculuk';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('isik-ve-renkler', 'Işık ve Renkler', 'Güneşli bir günde yağmur yağarken gökyüzünde beliren gökkuşağını izlemek, doğanın sunduğu en güzel manzaralardan biridir. Kırmızıdan mora uzanan bu renk şeridi, ışığın bize anlattığı büyüleyici bir hikâyenin parçasıdır. Bu hikâyeyi anlamak için önce ışığın ne olduğunu düşünmemiz gerekir.

Işık, evrende bilinen en hızlı şeydir. Saniyede yaklaşık üç yüz bin kilometre yol alır. Bu hızla giden bir ışık ışını, yalnızca bir saniyede Dünya''nın çevresini yedi kereden fazla dolaşabilir. Işık sayesinde çevremizdeki nesneleri görürüz. Çünkü bir nesneden yansıyan ışık gözümüze ulaşır ve beynimiz bu bilgiyi bir görüntüye dönüştürür.

Güneş''ten gelen ışığı beyaz ya da renksiz olarak algılarız. Oysa bu ışık aslında birçok rengin karışımıdır. Bunu deneylerle açıklayan ilk bilim insanlarından biri İngiliz bilim insanı Isaac Newton''dır. Newton, karanlık bir odaya giren ince bir güneş ışınının önüne prizma adı verilen üçgen biçimli bir cam parçası koydu. Işık prizmadan geçerken kırıldı ve duvarda kırmızı, turuncu, sarı, yeşil, mavi ve mor renklerden oluşan bir şerit belirdi. Newton böylece beyaz ışığın renklere ayrılabildiğini gösterdi.

Gökkuşağı da benzer şekilde oluşur. Havadaki milyonlarca yağmur damlası, küçük birer prizma gibi davranır. Güneş ışığı damlalara girip çıkarken kırılır ve renklerine ayrılır. Bu yüzden gökkuşağını görebilmek için Güneş''in arkamızda, yağmurun ise önümüzde olması gerekir.

Peki bir elma neden kırmızı görünür? Elmanın yüzeyi, üzerine düşen ışıktaki renklerin çoğunu emer, yalnızca kırmızıyı yansıtır. Gözümüze ulaşan bu kırmızı ışık, elmayı kırmızı görmemizi sağlar. Beyaz nesneler bütün renkleri yansıtırken siyah nesneler neredeyse hepsini emer. Güneşli bir günde siyah bir tişörtün beyaz bir tişörtten daha çok ısınmasının nedeni de budur.

Kısacası çevremizdeki renkli dünya, ışık ile nesneler arasındaki sessiz bir iş birliğinin sonucudur.', 'Bilim', 5, 4, 257, 193, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Beyaz ışığın renklere ayrılabildiğini prizma deneyiyle gösteren bilim insanı kimdir?', 'Galileo Galilei', 'Albert Einstein', 'Isaac Newton', 'Marie Curie', 'c', 'Newton, prizma deneyiyle beyaz ışığın renklere ayrılabildiğini gösterdi.' FROM texts WHERE slug = 'isik-ve-renkler';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metne göre prizma nedir?', 'Üçgen biçimli bir cam parçası', 'Bir çeşit mercek gözlük', 'Işık üreten bir lamba', 'Renkli bir boya', 'a', 'Metinde prizmanın üçgen biçimli bir cam parçası olduğu açıklanıyor.' FROM texts WHERE slug = 'isik-ve-renkler';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Gökkuşağını görebilmek için Güneş ve yağmur nerede olmalıdır?', 'İkisi de önümüzde olmalıdır.', 'Güneş önümüzde, yağmur arkamızda olmalıdır.', 'İkisi de arkamızda olmalıdır.', 'Güneş arkamızda, yağmur önümüzde olmalıdır.', 'd', 'Metinde Güneş''in arkamızda, yağmurun önümüzde olması gerektiği yazıyor.' FROM texts WHERE slug = 'isik-ve-renkler';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Bir elma neden kırmızı görünür?', 'Kendi içinden kırmızı ışık çıkardığı için', 'Yalnızca kırmızı ışığı yansıtıp diğerlerini emdiği için', 'Bütün renkleri yansıttığı için', 'Bütün renkleri emdiği için', 'b', 'Elma, renklerin çoğunu emer ve yalnızca kırmızıyı yansıtır.' FROM texts WHERE slug = 'isik-ve-renkler';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Güneşli bir günde siyah tişört neden daha çok ısınır?', 'Işığın neredeyse tamamını emdiği için', 'Kumaşı daha kalın olduğu için', 'Işığın tamamını yansıttığı için', 'Rüzgârı tuttuğu için', 'a', 'Siyah nesneler ışığın neredeyse tamamını emer, bu yüzden daha çok ısınır.' FROM texts WHERE slug = 'isik-ve-renkler';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('hezarfen-efsanesi', 'Hezarfen Ahmed Çelebi Efsanesi', 'İnsanlar binlerce yıl boyunca gökyüzünde süzülen kuşları hayranlıkla izlemiş ve bir gün onlar gibi uçabilmeyi hayal etmiştir. Bu hayali gerçekleştirmeye çalıştığı anlatılanlar arasında, ülkemizde en çok bilinen isimlerden biri Hezarfen Ahmed Çelebi''dir.

Hezarfen Ahmed Çelebi''nin on yedinci yüzyılda İstanbul''da yaşadığı anlatılır. "Hezarfen" kelimesi, "bin fenli" yani pek çok bilgiye ve beceriye sahip kişi anlamına gelir. Onun hakkında bildiklerimizin neredeyse tamamı, ünlü gezgin Evliya Çelebi''nin Seyahatname adlı eserinden gelir. Evliya Çelebi, Hezarfen''in uçuşunu kitabında kısa bir bölüm hâlinde anlatmıştır.

Anlatılana göre Hezarfen, uçmadan önce uzun süre kuşları gözlemlemiştir. Kanatlarının hareketini ve rüzgârı nasıl kullandıklarını incelemiş, kendine kartal kanatlarını andıran bir çift kanat hazırlamıştır. Denemelerini önce Okmeydanı''nda yapmıştır. Sonra bir gün, rüzgârın uygun olduğu bir anda, Galata Kulesi''nin tepesinden atlamıştır. Evliya Çelebi''ye göre Hezarfen, İstanbul Boğazı''nın üzerinden süzülerek karşı kıyıda, Üsküdar''daki Doğancılar Meydanı''na inmiştir.

Hikâyeye göre bu uçuşu izleyen Padişah IV. Murad, Hezarfen''i bir kese altınla ödüllendirmiştir. Ancak böylesine yetenekli birinin tehlikeli olabileceğini düşünerek onu Cezayir''e göndermiştir.

Bugün tarihçiler, bu uçuşun anlatıldığı gibi gerçekleşip gerçekleşmediğinden emin değildir. Galata Kulesi ile Doğancılar arasındaki mesafe üç kilometreden fazladır ve olayı doğrulayan başka bir kaynak bulunmamaktadır. Bu nedenle Hezarfen''in uçuşu, kesin bir tarihî olaydan çok bir efsane olarak kabul edilir.

Yine de bu efsane, önemli bir düşünceyi anlatır: Büyük buluşlar, merak eden, gözlem yapan ve cesurca deneyen insanların hayalleriyle başlar. Nitekim anlatılan uçuştan yaklaşık 270 yıl sonra, 1903 yılında Wright kardeşler motorlu bir uçakla havalanmayı başardı. İstanbul''daki küçük bir havalimanına Hezarfen''in adının verilmiş olması da bu hayale duyulan saygının bir göstergesidir.', 'Tarih', 5, 4, 246, 185, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, '"Hezarfen" kelimesi ne anlama gelir?', 'Kuş gibi uçan', 'Bin fenli, yani pek çok bilgiye ve beceriye sahip', 'Cesur savaşçı', 'Kule bekçisi', 'b', 'Metinde Hezarfen kelimesinin "bin fenli" anlamına geldiği açıklanıyor.' FROM texts WHERE slug = 'hezarfen-efsanesi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Hezarfen hakkındaki bilgilerin neredeyse tamamı hangi kaynaktan gelir?', 'Piri Reis''in Kitab-ı Bahriye''sinden', 'Padişahın mektuplarından', 'Gazete haberlerinden', 'Evliya Çelebi''nin Seyahatname''sinden', 'd', 'Bilgilerimizin neredeyse tamamı Evliya Çelebi''nin Seyahatname adlı eserinden gelir.' FROM texts WHERE slug = 'hezarfen-efsanesi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Anlatılana göre Hezarfen nereye inmiştir?', 'Üsküdar''daki Doğancılar Meydanı''na', 'Okmeydanı''na', 'Galata Kulesi''nin bahçesine', 'Cezayir''e', 'a', 'Evliya Çelebi''ye göre Hezarfen, Üsküdar''daki Doğancılar Meydanı''na inmiştir.' FROM texts WHERE slug = 'hezarfen-efsanesi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Hezarfen''in uçuşu neden bir efsane olarak kabul edilir?', 'Hezarfen hiç yaşamadığı için', 'Uçuş bir masal kitabında anlatıldığı için', 'Olayı doğrulayan başka bir kaynak olmadığı ve mesafe çok uzun olduğu için', 'Wright kardeşler bunu yalanladığı için', 'c', 'Mesafe üç kilometreden fazladır ve olayı doğrulayan başka bir kaynak yoktur.' FROM texts WHERE slug = 'hezarfen-efsanesi';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metnin ana fikri nedir?', 'Galata Kulesi çok yüksektir.', 'Padişahlar mucitleri hep ödüllendirmiştir.', 'Uçmak çok tehlikeli bir iştir.', 'Büyük buluşlar merak eden ve cesurca deneyen insanların hayalleriyle başlar.', 'd', 'Metnin son bölümü, efsanenin anlattığı bu önemli düşünceyi vurguluyor.' FROM texts WHERE slug = 'hezarfen-efsanesi';

INSERT INTO texts (slug, title, content, category, difficulty, grade_level, word_count, estimated_duration, source_type, is_placement) VALUES ('yildizlarin-yasami', 'Yıldızların Yaşamı', 'Açık bir gecede şehir ışıklarından uzak bir yerde gökyüzüne bakarsak binlerce yıldız görebiliriz. Bu yıldızlar gökyüzünde hep aynı yerde duruyormuş gibi görünür. Oysa her yıldızın, tıpkı canlılar gibi, bir doğuşu, uzun bir yaşamı ve bir sonu vardır. Yalnız bir yıldızın yaşamı milyonlarca, hatta milyarlarca yıl sürer.

Yıldızlar, uzayda bulutsu adı verilen dev gaz ve toz bulutlarının içinde doğar. Bulutsunun bazı bölgelerinde gaz ve toz, kütle çekimi sayesinde yavaş yavaş bir araya toplanır. Madde sıkıştıkça ısınır. Merkezdeki sıcaklık milyonlarca dereceye ulaştığında hidrojen atomları birleşerek helyuma dönüşmeye başlar. Bu olay büyük bir enerji açığa çıkarır ve yeni bir yıldız parlamaya başlar.

Güneş''imiz de böyle doğmuş orta büyüklükte bir yıldızdır. Yaklaşık 4,6 milyar yaşındadır ve bilim insanlarına göre yaklaşık beş milyar yıl daha parlamaya devam edecektir. Yakıtı azaldığında Güneş şişerek kırmızı bir deve dönüşecek, ardından dış katmanlarını uzaya savuracaktır. Geriye beyaz cüce adı verilen küçük ve zamanla sönükleşen bir yıldız kalacaktır.

Güneş''ten çok daha büyük kütleli yıldızların sonu ise çok daha görkemlidir. Bu yıldızlar yakıtlarını daha hızlı tüketir ve yaşamlarını süpernova adı verilen dev bir patlamayla bitirir. Bir süpernova, kısa bir süre için koca bir galaksi kadar parlak görünebilir. Patlamadan geriye son derece yoğun bir nötron yıldızı ya da ışığın bile kaçamadığı bir kara delik kalabilir.

Yıldızların yaşamı bizim için de önemlidir. Vücudumuzdaki karbon, soluduğumuz havadaki oksijen ve kanımızdaki demir gibi elementler, çok uzun zaman önce yıldızların içinde oluşmuştur. Bu elementler, yaşamını tamamlayan yıldızların uzaya saçtığı maddelerle yeni yıldızlara ve gezegenlere taşınmıştır. Bu yüzden bazı bilim insanları, hepimizin aslında yıldız tozundan yapıldığını söyler.

Bir dahaki sefere yıldızlara baktığınızda, onların bizim çok uzak akrabalarımız olduğunu hatırlayın.', 'Uzay', 5, 4, 262, 197, 'system', 0);
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Yıldızlar nerede doğar?', 'Bulutsu adı verilen dev gaz ve toz bulutlarında', 'Gezegenlerin içinde', 'Kara deliklerin merkezinde', 'Ay''ın yüzeyinde', 'a', 'Yıldızlar, bulutsu adı verilen dev gaz ve toz bulutlarının içinde doğar.' FROM texts WHERE slug = 'yildizlarin-yasami';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Güneş yaklaşık kaç yaşındadır?', 'Beş bin yaşında', 'Bir milyon yaşında', '4,6 milyar yaşında', 'Yüz milyar yaşında', 'c', 'Metinde Güneş''in yaklaşık 4,6 milyar yaşında olduğu yazıyor.' FROM texts WHERE slug = 'yildizlarin-yasami';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Güneş''ten çok daha büyük kütleli yıldızlar yaşamlarını nasıl bitirir?', 'Yavaşça soğuyarak', 'Gezegene dönüşerek', 'Buz tutarak', 'Süpernova adı verilen dev bir patlamayla', 'd', 'Büyük kütleli yıldızlar yaşamlarını süpernova patlamasıyla bitirir.' FROM texts WHERE slug = 'yildizlarin-yasami';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Bazı bilim insanları neden hepimizin yıldız tozundan yapıldığını söyler?', 'Geceleri yıldızlara baktığımız için', 'Vücudumuzdaki bazı elementler yıldızların içinde oluştuğu için', 'Uzaydan toz yağdığı için', 'Güneş bizi ısıttığı için', 'b', 'Karbon, oksijen ve demir gibi elementler yıldızların içinde oluşmuştur.' FROM texts WHERE slug = 'yildizlarin-yasami';
INSERT INTO questions (text_id, question, option_a, option_b, option_c, option_d, correct_option, explanation) SELECT id, 'Metne göre Güneş''in yaşamının sonunda geriye ne kalacaktır?', 'Bir kara delik', 'Bir nötron yıldızı', 'Bir beyaz cüce', 'Yeni bir gezegen', 'c', 'Güneş dış katmanlarını savurduktan sonra geriye bir beyaz cüce kalacaktır.' FROM texts WHERE slug = 'yildizlarin-yasami';

INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('first_reading', 'İlk Adım', 'İlk okumanı tamamladın.', 'Footprints', 'readings', 1, 1);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('readings_10', 'Kitap Kurdu', '10 okuma tamamladın.', 'BookOpen', 'readings', 10, 2);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('readings_50', 'Okuma Ustası', '50 okuma tamamladın.', 'Library', 'readings', 50, 3);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('streak_3', 'Üç Gün Üst Üste', '3 gün arka arkaya çalıştın.', 'Flame', 'streak', 3, 4);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('streak_7', 'Haftalık Seri', '7 gün arka arkaya çalıştın.', 'CalendarCheck', 'streak', 7, 5);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('streak_30', 'Ay Yıldızı', '30 gün arka arkaya çalıştın.', 'Moon', 'streak', 30, 6);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('perfect_comprehension', 'Dikkatli Okur', 'Bir metnin tüm sorularını doğru cevapladın.', 'Brain', 'perfect_comprehension', 1, 7);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('comprehension_5', 'Anlama Şampiyonu', '5 okumada %80 ve üzeri anlama yaptın.', 'Lightbulb', 'good_comprehension', 5, 8);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('words_1000', 'Bin Kelime', 'Toplam 1.000 kelime okudun.', 'Type', 'words', 1000, 9);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('words_10000', 'On Bin Kelime', 'Toplam 10.000 kelime okudun.', 'Mountain', 'words', 10000, 10);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('repeat_reader', 'Tekrar Tekrar', 'Bir metni 3 kez okudun.', 'Repeat', 'third_attempt', 1, 11);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('fluency_up', 'Akıcı Okur', 'Tekrar okumada ilk okumana göre %15 daha akıcı okudun.', 'TrendingUp', 'improvement', 15, 12);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('games_10', 'Oyun Sever', '10 kelime oyunu tamamladın.', 'Gamepad2', 'games', 10, 13);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('xp_500', 'Parlayan Yıldız', '500 XP topladın.', 'Star', 'xp', 500, 14);
INSERT INTO achievements (id, title, description, icon, criteria_type, criteria_value, sort_order) VALUES ('all_categories', 'Kâşif', 'Her kategoriden en az bir metin okudun.', 'Compass', 'categories', 10, 15);
